select * from blinkit limit 20;

-- Q1. WHAT IS THE TOTAL REVENUE GENERATED BY EACH OUTLET TYPE?
SELECT outlet_type, 
       ROUND(SUM(sales)::numeric, 2) AS total_revenue
FROM blinkit
GROUP BY outlet_type
ORDER BY total_revenue DESC;


-- Q2. WHICH OUTLET LOCATION TYPE GENERATES THE HIGHEST REVENUE?
SELECT outlet_location_type,
       ROUND(SUM(sales)::numeric, 2) AS total_revenue
FROM blinkit
GROUP BY outlet_location_type
ORDER BY total_revenue DESC;


-- Q3. WHAT ARE THE TOP 5 HIGHEST SELLING ITEM TYPES?
SELECT item_type,
       ROUND(SUM(sales)::numeric, 2) AS total_sales
FROM blinkit
GROUP BY item_type
ORDER BY total_sales DESC
LIMIT 5;


-- Q4. WHICH ITEM FAT CONTENT HAS HIGHER TOTAL SALES?
SELECT item_fat_content,
       ROUND(SUM(sales)::numeric, 2) AS total_sales,
       ROUND(AVG(sales)::numeric, 2) AS avg_sales
FROM blinkit
GROUP BY item_fat_content
ORDER BY total_sales DESC;


-- Q5. WHAT IS THE AVERAGE RATING FOR EACH ITEM TYPE?
SELECT item_type,
       ROUND(AVG(rating)::numeric, 2) AS avg_rating
FROM blinkit
GROUP BY item_type
ORDER BY avg_rating DESC;


-- Q6. WHICH OUTLET SIZE GENERATES THE MOST REVENUE?
SELECT outlet_size,
       ROUND(SUM(sales)::numeric, 2) AS total_revenue,
       COUNT(*) AS total_items
FROM blinkit
GROUP BY outlet_size
ORDER BY total_revenue DESC;


-- Q7. HOW HAS SALES PERFORMED ACROSS DIFFERENT OUTLET ESTABLISHMENT YEARS?
SELECT outlet_establishment_year,
       ROUND(SUM(sales)::numeric, 2) AS total_sales,
       COUNT(DISTINCT outlet_identifier) AS total_outlets
FROM blinkit
GROUP BY outlet_establishment_year
ORDER BY outlet_establishment_year;


-- Q8. WHAT ARE THE TOP 3 BEST SELLING ITEMS WITHIN EACH ITEM TYPE?
WITH item_sales AS (
    SELECT item_type,
           item_identifier,
           ROUND(SUM(sales)::numeric, 2) AS total_sales,
           ROW_NUMBER() OVER(PARTITION BY item_type 
                             ORDER BY SUM(sales) DESC) AS item_rank
    FROM blinkit
    GROUP BY item_type, item_identifier
)
SELECT item_rank, item_type, item_identifier, total_sales
FROM item_sales
WHERE item_rank <= 3
ORDER BY item_type, item_rank;


-- Q9. DO HIGH VISIBILITY ITEMS GENERATE MORE SALES?
SELECT 
    CASE 
        WHEN item_visibility >= 0.1 THEN 'High Visibility'
        WHEN item_visibility BETWEEN 0.05 AND 0.1 THEN 'Medium Visibility'
        ELSE 'Low Visibility'
    END AS visibility_segment,
    COUNT(*) AS total_items,
    ROUND(AVG(sales)::numeric, 2) AS avg_sales,
    ROUND(SUM(sales)::numeric, 2) AS total_sales
FROM blinkit
GROUP BY visibility_segment
ORDER BY avg_sales DESC;


-- Q10. WHICH COMBINATION OF OUTLET TYPE AND LOCATION TYPE PERFORMS THE BEST?
SELECT outlet_type,
       outlet_location_type,
       ROUND(SUM(sales)::numeric, 2) AS total_sales,
       ROUND(AVG(sales)::numeric, 2) AS avg_sales,
       COUNT(*) AS total_items
FROM blinkit
GROUP BY outlet_type, outlet_location_type
ORDER BY total_sales DESC;